import datetime

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.decorators.http import require_GET
from django.core.cache import cache
from django.conf import settings as django_settings

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group

User = get_user_model()
from gate.models import EventCategory, Event, Student, GateEntry, GateIncident, AuditLog, GateShift, StaffPersonnelProfile
from gate.gate_views import _granted_visits_count_for_date, _local_day_bounds, _local_year_bounds
from .forms import (
    LoginForm,
    StaffPersonnelRegistrationForm,
    StaffPersonnelCompleteProfileForm,
    UserProfileEditForm,
    AccountDetailsForm,
    UserPreferencesForm,
    PhoneResetRequestForm,
    VerifyCodeForm,
    NewPasswordForm,
    PasswordResetFormEmailOrUsername,
    _normalize_phone,
)
from .roles import get_user_role, role_required


@require_GET
def privacy_policy(request):
    """Public privacy & data policy page (no login required)."""
    return render(request, 'legal/privacy_policy.html', {
        'site_name': 'City College of Bayawan',
    })


@require_GET
def terms_and_conditions(request):
    """Public terms and conditions page (no login required)."""
    return render(request, 'legal/terms_and_conditions.html', {
        'site_name': 'City College of Bayawan',
    })


@require_GET
def health_check(request):
    """Lightweight health/readiness check: 200 if app and DB are up. For monitoring/load balancers."""
    from django.http import HttpResponse
    from django.db import connection
    try:
        connection.ensure_connection()
        return HttpResponse('ok', content_type='text/plain', status=200)
    except Exception:
        return HttpResponse('unavailable', content_type='text/plain', status=503)


@require_GET
def login_probe(request):
    """Minimal HTML (no large templates). Use through ngrok/LAN to confirm routing before debugging /login/."""
    from django.http import HttpResponse
    html = (
        '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        '<title>Reachability</title></head><body style="font-family:system-ui,sans-serif;padding:1.5rem;max-width:40rem;">'
        '<h1>Django is responding</h1>'
        '<p>If you see this through your tunnel, HTTP routing and ALLOWED_HOSTS are OK.</p>'
        '<p><a href="/login/">Open login page</a> · <a href="/">Open home</a></p>'
        '</body></html>'
    )
    return HttpResponse(html, content_type='text/html; charset=utf-8', status=200)


@require_GET
def ngrok_tunnel_help(request):
    """Explains ngrok free-tier interstitial (not a Django bug). Linked from docs and README."""
    from django.http import HttpResponse
    html = """<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ngrok free tier &amp; this app</title></head>
<body style="font-family:system-ui,sans-serif;padding:1.25rem 1.5rem;max-width:42rem;line-height:1.5;color:#1a1a1a;">
<h1 style="margin-top:0;">Why the tunnel can look &ldquo;blank&rdquo;</h1>
<p><strong>ngrok Free</strong> injects an <strong>interstitial warning page</strong> before your app (anti-phishing).
It is <strong>not</strong> generated by Django. If scripts or cookies are blocked, the page can look white or empty.</p>
<p><strong>Official bypass (browser):</strong> click <strong>Visit</strong> / continue on that page. ngrok sets a cookie for ~7 days so the warning may not repeat for that domain.</p>
<p><strong>Official bypass (dev tools):</strong> send header <code>ngrok-skip-browser-warning: 1</code> on requests
(e.g. Chrome extension &ldquo;ModHeader&rdquo; for <code>*.ngrok-free.dev</code>), or use a <strong>non-standard User-Agent</strong>
(see <a href="https://ngrok.com/docs/pricing-limits/free-plan-limits/#removing-the-interstitial-page" rel="noopener noreferrer">ngrok docs</a>).</p>
<p><strong>Upgrade:</strong> paid ngrok plans remove the interstitial.</p>
<hr style="border:none;border-top:1px solid #ddd;margin:1.25rem 0;">
<p style="margin-bottom:.5rem;">If you already passed the warning and still see nothing, test this app:</p>
<ul>
<li><a href="/ping/">/ping/</a> &mdash; plain text <code>ok</code></li>
<li><a href="/login-probe/">/login-probe/</a> &mdash; minimal HTML</li>
<li><a href="/login/">/login/</a> &mdash; full login</li>
</ul>
<p style="font-size:.9rem;color:#555;">Project doc: <code>docs/NGROK_FREE_TIER_INTERSTITIAL.md</code></p>
</body></html>"""
    return HttpResponse(html, content_type='text/html; charset=utf-8', status=200)


def custom_page_not_found_view(request, exception):
    """Branded 404 page."""
    return render(request, 'errors/404.html', {'site_name': 'City College of Bayawan'}, status=404)


def custom_server_error_view(request):
    """Branded 500 page."""
    return render(request, 'errors/500.html', {'site_name': 'City College of Bayawan'}, status=500)


# --- Phone-based password reset (send code → verify code → set new password) ---
PW_RESET_CACHE_PREFIX = 'pw_reset_phone_'
PW_RESET_CACHE_TIMEOUT = 600  # 10 minutes
SESSION_KEY_PHONE = 'password_reset_phone'
SESSION_KEY_USER_ID = 'password_reset_user_id'


def _get_user_by_phone(normalized_phone):
    """Return User for staff profile whose contact_number normalizes to this phone, or None."""
    if not normalized_phone:
        return None
    for profile in StaffPersonnelProfile.objects.select_related('user').filter(user__is_active=True):
        if _normalize_phone(profile.contact_number) == normalized_phone:
            return profile.user
    return None


def _send_verification_code_sms(phone_normalized, code):
    """
    Send SMS with verification code. Tries, in order:
    1. PHONE_RESET_SEND_SMS in settings (callable(phone, code))
    2. Semaphore (Philippines) if SEMAPHORE_API_KEY is set
    3. Twilio if TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_PHONE_NUMBER are set
    4. In DEBUG, only log; code can be shown on next page for testing
    """
    import os
    import requests
    import logging
    log = logging.getLogger(__name__)
    body = f'Your password reset code is: {code}. Valid for 10 minutes.'

    send_sms = getattr(django_settings, 'PHONE_RESET_SEND_SMS', None)
    if callable(send_sms):
        send_sms(phone_normalized, code)
        return

    # 1) Semaphore (Philippines) – api.semaphore.co
    api_key = os.environ.get('SEMAPHORE_API_KEY')
    if api_key:
        try:
            # Philippine format: 09XXXXXXXXX (11 digits). Strip country code if present.
            n = phone_normalized[-10:] if len(phone_normalized) >= 10 else phone_normalized
            num = ('0' + n) if n.startswith('9') else n
            sendername = (os.environ.get('SEMAPHORE_SENDER_NAME') or 'CCB')[:11]
            r = requests.post(
                'https://api.semaphore.co/api/v4/messages',
                data={'apikey': api_key, 'number': num, 'message': body, 'sendername': sendername},
                timeout=15,
            )
            if r.status_code == 200:
                if django_settings.DEBUG:
                    log.info('SMS sent via Semaphore to %s', num)
                return
            if django_settings.DEBUG:
                log.warning('Semaphore SMS failed (%s): %s', r.status_code, (r.text or '')[:500])
        except Exception:
            if django_settings.DEBUG:
                log.exception('Semaphore SMS exception')

    # 2) Twilio
    sid = os.environ.get('TWILIO_ACCOUNT_SID')
    token = os.environ.get('TWILIO_AUTH_TOKEN')
    from_num = os.environ.get('TWILIO_PHONE_NUMBER') or os.environ.get('TWILIO_FROM_NUMBER')
    if sid and token and from_num:
        try:
            to_num = phone_normalized if phone_normalized.startswith('+') else '+63' + phone_normalized.lstrip('0')
            r = requests.post(
                f'https://api.twilio.com/2010-04-01/Accounts/{sid}/Messages.json',
                auth=(sid, token),
                data={'To': to_num, 'From': from_num, 'Body': body},
                timeout=10,
            )
            if r.status_code in (200, 201):
                if django_settings.DEBUG:
                    log.info('SMS sent via Twilio to %s (from %s)', to_num, from_num)
                return
            if django_settings.DEBUG:
                log.warning('Twilio SMS failed (%s): %s', r.status_code, (r.text or '')[:500])
        except Exception:
            if django_settings.DEBUG:
                log.exception('Twilio SMS exception')

    if django_settings.DEBUG:
        log.info('Password reset verification code for %s: %s', phone_normalized, code)


def password_reset_phone_view(request):
    """
    Phone reset flow disabled (templates removed). Redirect to main password reset.
    """
    return redirect('password_reset')


def _mask_phone(phone_normalized):
    """Return last 4 digits visible, e.g. *******1234."""
    if len(phone_normalized) <= 4:
        return phone_normalized
    return '*' * (len(phone_normalized) - 4) + phone_normalized[-4:]


PER_PAGE_OPTIONS = [10, 20, 30, 40, 50, 100]


def _get_per_page_and_query(request):
    """Return (per_page, query_extra, query_extra_base). Default per_page 10."""
    raw = request.GET.get('per_page', '10')
    try:
        per_page = int(raw)
        if per_page not in PER_PAGE_OPTIONS:
            per_page = 10
    except (ValueError, TypeError):
        per_page = 10
    q_extra = request.GET.copy()
    q_extra.pop('page', None)
    query_extra = q_extra.urlencode()
    q_base = request.GET.copy()
    q_base.pop('page', None)
    q_base.pop('per_page', None)
    query_extra_base = q_base.urlencode()
    return per_page, query_extra, query_extra_base


@login_required(login_url='login')
@role_required('admin')
def user_list(request):
    """List app users with roles (admin only). Paginated."""
    from django.core.paginator import Paginator
    per_page, query_extra, query_extra_base = _get_per_page_and_query(request)
    qs = User.objects.all().order_by('username')
    paginator = Paginator(qs, per_page)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    users_list = [{'user': u, 'role': get_user_role(u) or '—'} for u in page_obj.object_list]
    return render(request, 'users/user_list.html', {
        'site_name': 'City College of Bayawan',
        'users_list': users_list,
        'page_obj': page_obj,
        'query_extra': query_extra,
        'query_extra_base': query_extra_base,
        'per_page': per_page,
        'per_page_options': PER_PAGE_OPTIONS,
    })

@login_required(login_url='login')
@role_required('admin', 'faculty', 'staff', 'supervisor')
def dashboard(request):
    today = timezone.localdate()
    cache_seconds = getattr(django_settings, 'CACHE_DASHBOARD_SECONDS', 120)
    cache_key = f'dashboard_counts_{today.isoformat()}'
    counts = cache.get(cache_key)
    if counts is None:
        day_start, day_end = _local_day_bounds(today)
        granted_today = _granted_visits_count_for_date(today, daily_gate_only=True)
        denied_entries_count = GateEntry.objects.filter(timestamp__gte=day_start, timestamp__lt=day_end, granted=False).count()
        incidents_today = GateIncident.objects.filter(timestamp__gte=day_start, timestamp__lt=day_end).count()
        denied_today = max(denied_entries_count, incidents_today)
        total_students = Student.objects.filter(is_active=True).count()
        first_of_month = today.replace(day=1)
        month_start_bounds, _ = _local_day_bounds(first_of_month)
        student_entries_this_month = GateEntry.objects.filter(
            timestamp__gte=month_start_bounds,
            timestamp__lt=day_end,
            granted=True,
            student_id__isnull=False,
            event__isnull=True,
            visitor_visit__isnull=True,
        ).count()
        ys, ye = _local_year_bounds(today.year)
        student_entries_this_year = GateEntry.objects.filter(
            timestamp__gte=ys,
            timestamp__lt=ye,
            granted=True,
            student_id__isnull=False,
            event__isnull=True,
            visitor_visit__isnull=True,
        ).count()
        counts = {
            'granted_today': granted_today,
            'denied_today': denied_today,
            'incidents_today': incidents_today,
            'total_students': total_students,
            'student_entries_this_month': student_entries_this_month,
            'student_entries_this_year': student_entries_this_year,
        }
        cache.set(cache_key, counts, cache_seconds)
    else:
        granted_today = counts['granted_today']
        denied_today = counts['denied_today']
        incidents_today = counts['incidents_today']
        total_students = counts['total_students']
        student_entries_this_month = counts.get('student_entries_this_month', 0)
        student_entries_this_year = counts.get('student_entries_this_year', 0)
    user = User.objects.count()
    event_ctg = EventCategory.objects.count()
    event = Event.objects.count()
    complete_event = Event.objects.filter(status='completed').count()
    events = Event.objects.all()
    # Staff currently on duty (clocked in via shift / gate dashboard)
    personnel_on_duty_list = list(GateShift.objects.filter(shift_end__isnull=True).select_related('personnel').order_by('-shift_start'))
    year_end_for_link = min(datetime.date(today.year, 12, 31), today)
    context = {
        'user': user,
        'event_ctg': event_ctg,
        'event': event,
        'complete_event': complete_event,
        'events': events,
        'today': today,
        'site_name': 'City College of Bayawan',
        'granted_today': granted_today,
        'denied_today': denied_today,
        'incidents_today': incidents_today,
        'total_students': total_students,
        'student_entries_this_month': student_entries_this_month,
        'student_entries_this_year': student_entries_this_year,
        'student_entries_month_from': today.replace(day=1).isoformat(),
        'student_entries_month_to': today.isoformat(),
        'student_entries_year_from': datetime.date(today.year, 1, 1).isoformat(),
        'student_entries_year_to': year_end_for_link.isoformat(),
        'dashboard_student_year': today.year,
        'personnel_on_duty_list': personnel_on_duty_list,
        'personnel_on_duty_count': len(personnel_on_duty_list),
    }
    return render(request, 'dashboard/dashboard.html', context)


@login_required(login_url='login')
@role_required('admin', 'faculty', 'staff', 'supervisor')
def dashboard_stats_api(request):
    """
    API endpoint for real-time dashboard stats updates.
    Returns JSON with current counts.
    """
    from django.http import JsonResponse
    
    today = timezone.localdate()
    day_start, day_end = _local_day_bounds(today)
    
    # Get fresh counts (no cache for real-time)
    # Count ALL granted entries (students + visitors + events)
    granted_today = GateEntry.objects.filter(
        timestamp__gte=day_start, 
        timestamp__lt=day_end, 
        granted=True
    ).count()
    
    denied_entries_count = GateEntry.objects.filter(
        timestamp__gte=day_start, 
        timestamp__lt=day_end, 
        granted=False
    ).count()
    incidents_today = GateIncident.objects.filter(
        timestamp__gte=day_start, 
        timestamp__lt=day_end
    ).count()
    denied_today = max(denied_entries_count, incidents_today)
    total_students = Student.objects.filter(is_active=True).count()
    
    # Staff on duty count
    personnel_on_duty_count = GateShift.objects.filter(shift_end__isnull=True).count()

    first_of_month = today.replace(day=1)
    month_start_bounds, _ = _local_day_bounds(first_of_month)
    student_entries_this_month = GateEntry.objects.filter(
        timestamp__gte=month_start_bounds,
        timestamp__lt=day_end,
        granted=True,
        student_id__isnull=False,
        event__isnull=True,
        visitor_visit__isnull=True,
    ).count()
    ys, ye = _local_year_bounds(today.year)
    student_entries_this_year = GateEntry.objects.filter(
        timestamp__gte=ys,
        timestamp__lt=ye,
        granted=True,
        student_id__isnull=False,
        event__isnull=True,
        visitor_visit__isnull=True,
    ).count()

    from gate.gate_personnel_services import RealtimeDashboardService
    from gate.gate_personnel_views import GATE_STAFF_SCANNER_HEARTBEAT_CACHE_KEY

    stats = RealtimeDashboardService.get_current_stats()
    inside_now = stats['currently_inside']

    last_entry = GateEntry.objects.filter(
        timestamp__gte=day_start,
        timestamp__lt=day_end,
    ).order_by('-timestamp').first()
    if last_entry:
        last_scan_label = timezone.localtime(last_entry.timestamp).strftime('%Y-%m-%d %H:%M')
    else:
        last_scan_label = 'No scans yet today'

    scanner_status = 'ACTIVE' if cache.get(GATE_STAFF_SCANNER_HEARTBEAT_CACHE_KEY) else 'IDLE'

    recent_qs = GateEntry.objects.filter(
        timestamp__gte=day_start,
        timestamp__lt=day_end,
    ).select_related('student', 'visitor_visit').order_by('-timestamp')[:12]
    recent_activity = []
    for e in recent_qs:
        if e.student_id:
            who = e.student.get_full_name()
        elif e.visitor_visit_id:
            who = e.visitor_visit.full_name
        else:
            who = (e.notes or 'Unknown')[:120]
        recent_activity.append({
            'student_name': who,
            'action': (e.scan_type or 'IN').upper(),
            'time': timezone.localtime(e.timestamp).strftime('%Y-%m-%d %H:%M'),
        })

    return JsonResponse({
        'success': True,
        'granted_today': granted_today,
        'denied_today': denied_today,
        'incidents_today': incidents_today,
        'total_students': total_students,
        'personnel_on_duty_count': personnel_on_duty_count,
        'student_entries_this_month': student_entries_this_month,
        'student_entries_this_year': student_entries_this_year,
        'inside_now': inside_now,
        'last_scan_label': last_scan_label,
        'scanner_status': scanner_status,
        'recent_activity': recent_activity,
    })


def login_page(request):
    from django.contrib import messages
    from gate.forms import StudentRegistrationForm
    forms = LoginForm()
    reg_form = StudentRegistrationForm()
    next_url = request.GET.get('next', '')
    if request.method == 'POST':
        forms = LoginForm(request.POST)
        if forms.is_valid():
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                if not user.is_active:
                    forms.add_error(None, 'Your account is pending approval. An administrator must approve it before you can log in.')
                else:
                    role = get_user_role(user)
                    if role is None:
                        messages.error(request, 'Your account has no role (Admin, Staff, Faculty, or Supervisor). Contact the administrator.')
                        return render(request, 'auth/login.html', {
                            'form': forms, 'next': next_url, 'reg_form': reg_form,
                            'staff_personnel_form': StaffPersonnelRegistrationForm(),
                            'site_name': 'City College of Bayawan'
                        })
                    login(request, user)
                    # Record login for admin "View logs"
                    try:
                        ip = (request.META.get('HTTP_X_FORWARDED_FOR') or '').split(',')[0].strip() or request.META.get('REMOTE_ADDR') or ''
                        AuditLog.objects.create(
                            user=user,
                            action='login',
                            description='User logged in',
                            ip_address=ip[:45] if ip else None,
                        )
                    except Exception:
                        pass
                    # Staff/Faculty must complete profile before full access
                    if role in ('staff', 'faculty'):
                        profile, _ = StaffPersonnelProfile.objects.get_or_create(
                            user=user, defaults={'profile_complete': False}
                        )
                        if not getattr(profile, 'profile_complete', False):
                            return redirect('staff-personnel-complete-profile')
                    redirect_to = (request.POST.get('next') or request.GET.get('next') or '').strip()
                    if not redirect_to:
                        role_after = get_user_role(user)
                        gate_first = getattr(django_settings, 'LOGIN_REDIRECT_GATE_FIRST_ROLES', ('staff', 'faculty', 'supervisor'))
                        if role_after in gate_first:
                            redirect_to = getattr(django_settings, 'LOGIN_REDIRECT_DEFAULT_GATE_STAFF', 'gate-scan')
                        else:
                            redirect_to = getattr(django_settings, 'LOGIN_REDIRECT_DEFAULT_ADMIN', 'dashboard')
                    return redirect(redirect_to)
            else:
                # Django's authenticate() returns None for inactive users; check if credentials are correct but account is pending approval
                try:
                    from django.contrib.auth import get_user_model
                    UserModel = get_user_model()
                    pending_user = UserModel.objects.get(username__iexact=username)
                    if not pending_user.is_active and pending_user.check_password(password):
                        forms.add_error(None, 'Your account is pending approval. An administrator must approve it before you can log in.')
                    else:
                        forms.add_error(None, 'Invalid username or password.')
                except UserModel.DoesNotExist:
                    forms.add_error(None, 'Invalid username or password.')
    context = {
        'form': forms,
        'next': next_url,
        'reg_form': reg_form,
        'staff_personnel_form': StaffPersonnelRegistrationForm(),
        'site_name': 'City College of Bayawan',
    }
    return render(request, 'auth/login.html', context)


@login_required
def profile_edit(request):
    """Edit profile for any authenticated user (admin, staff, faculty). Includes name, email, profile photo; staff/faculty also get extended profile fields."""
    from django.contrib import messages
    from gate.models import StaffPersonnelProfile, UserProfile

    user = request.user
    profile = getattr(user, 'staff_personnel_profile', None)
    has_profile = profile is not None
    user_profile, _ = UserProfile.objects.get_or_create(user=user, defaults={})
    current_avatar_url = user_profile.avatar.url if user_profile.avatar else None

    if request.method == 'POST':
        form = UserProfileEditForm(request.POST, request.FILES)
        if form.is_valid():
            user.first_name = (form.cleaned_data.get('first_name') or '').strip()[:150]
            user.last_name = (form.cleaned_data.get('last_name') or '').strip()[:150]
            email = (form.cleaned_data.get('email') or '').strip().lower()
            if email:
                user.email = email
            user.save(update_fields=['first_name', 'last_name', 'email'])
            if has_profile:
                profile.middle_name = (form.cleaned_data.get('middle_name') or '')[:100]
                profile.sex = (form.cleaned_data.get('sex') or '').strip() or ''
                profile.birthdate = form.cleaned_data.get('birthdate')
                profile.address = (form.cleaned_data.get('address') or '')[:500]
                profile.contact_number = (form.cleaned_data.get('contact_number') or '')[:20]
                profile.employee_id = (form.cleaned_data.get('employee_id') or '')[:50]
                profile.department = (form.cleaned_data.get('department') or '')[:150]
                profile.position = (form.cleaned_data.get('position') or '')[:150]
                profile.save(update_fields=[
                    'middle_name', 'sex', 'birthdate', 'address',
                    'contact_number', 'employee_id', 'department', 'position',
                ])
            new_avatar = form.cleaned_data.get('avatar')
            if new_avatar:
                if user_profile.avatar:
                    user_profile.avatar.delete(save=False)
                user_profile.avatar = new_avatar
                user_profile.save(update_fields=['avatar'])
            elif new_avatar is False and user_profile.avatar:
                user_profile.avatar.delete(save=False)
                user_profile.avatar = None
                user_profile.save(update_fields=['avatar'])
            messages.success(request, 'Your profile has been updated.')
            return redirect('profile-edit')
    else:
        initial = {
            'first_name': user.first_name or '',
            'last_name': user.last_name or '',
            'email': user.email or '',
        }
        if has_profile:
            initial.update({
                'middle_name': profile.middle_name or '',
                'sex': profile.sex or '',
                'birthdate': profile.birthdate,
                'address': profile.address or '',
                'contact_number': profile.contact_number or '',
                'employee_id': profile.employee_id or '',
                'department': profile.department or '',
                'position': profile.position or '',
            })
        form = UserProfileEditForm(initial=initial)

    return render(request, 'users/profile_edit.html', {
        'form': form,
        'has_profile': has_profile,
        'current_avatar_url': current_avatar_url,
        'site_name': 'City College of Bayawan',
    })


@login_required
def staff_personnel_complete_profile(request):
    """Required one-time profile completion for staff/faculty after first login. Blocks dashboard until filled."""
    from django.contrib import messages
    role = get_user_role(request.user)
    if role not in ('staff', 'faculty'):
        return redirect('dashboard')
    profile, _ = StaffPersonnelProfile.objects.get_or_create(user=request.user, defaults={})
    if profile.profile_complete:
        role_done = get_user_role(request.user)
        gate_first = getattr(django_settings, 'LOGIN_REDIRECT_GATE_FIRST_ROLES', ('staff', 'faculty', 'supervisor'))
        if role_done in gate_first:
            return redirect(getattr(django_settings, 'LOGIN_REDIRECT_DEFAULT_GATE_STAFF', 'gate-scan'))
        return redirect('dashboard')

    if request.method == 'POST':
        form = StaffPersonnelCompleteProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile.sex = (form.cleaned_data.get('sex') or '').strip()
            profile.birthdate = form.cleaned_data.get('birthdate')
            profile.address = (form.cleaned_data.get('address') or '').strip()[:500]
            profile.contact_number = (form.cleaned_data.get('contact_number') or '').strip()[:20]
            profile.employee_id = (form.cleaned_data.get('employee_id') or '').strip()[:50]
            profile.department = (form.cleaned_data.get('department') or '').strip()[:150]
            profile.position = (form.cleaned_data.get('position') or '').strip()[:150]
            profile.profile_complete = True
            profile.save(update_fields=[
                'sex', 'birthdate', 'address', 'contact_number',
                'employee_id', 'department', 'position', 'profile_complete',
            ])
            avatar_file = form.cleaned_data.get('photo')
            if avatar_file:
                from gate.models import UserProfile
                user_profile, _ = UserProfile.objects.get_or_create(user=request.user, defaults={})
                if user_profile.avatar:
                    user_profile.avatar.delete(save=False)
                user_profile.avatar = avatar_file
                user_profile.save(update_fields=['avatar'])
            messages.success(request, 'Your profile is complete.')
            role_after = get_user_role(request.user)
            gate_first = getattr(django_settings, 'LOGIN_REDIRECT_GATE_FIRST_ROLES', ('staff', 'faculty', 'supervisor'))
            if role_after in gate_first:
                return redirect(getattr(django_settings, 'LOGIN_REDIRECT_DEFAULT_GATE_STAFF', 'gate-scan'))
            return redirect('dashboard')
    else:
        form = StaffPersonnelCompleteProfileForm(initial={
            'sex': profile.sex or '',
            'birthdate': profile.birthdate,
            'address': profile.address or '',
            'contact_number': profile.contact_number or '',
            'employee_id': profile.employee_id or '',
            'department': profile.department or '',
            'position': profile.position or '',
        })

    return render(request, 'users/staff_guard_complete_profile.html', {
        'form': form,
        'site_name': 'City College of Bayawan',
        'user_role': role,
    })


@login_required
def account_settings(request):
    """Account details (username, email) only. For staff and faculty. Password change via login-page forgot password."""
    from django.contrib import messages
    user = request.user
    role = get_user_role(user)
    # Restrict to staff, faculty so students use their own portal if any
    if role not in ('staff', 'faculty'):
        return redirect('profile-edit')
    account_form = AccountDetailsForm(user=user)

    if request.method == 'POST':
        if request.POST.get('action') == 'save_account':
            account_form = AccountDetailsForm(request.POST, user=user)
            if account_form.is_valid():
                user.username = (account_form.cleaned_data['username'] or '').strip()[:150]
                user.email = (account_form.cleaned_data['email'] or '').strip().lower()
                user.save(update_fields=['username', 'email'])
                messages.success(request, 'Account details saved.')
                return redirect('account-settings')
        else:
            account_form = AccountDetailsForm(request.POST or None, user=user)
    else:
        account_form = AccountDetailsForm(initial={
            'username': user.username or '',
            'email': user.email or '',
        }, user=user)

    return render(request, 'users/account_settings.html', {
        'account_form': account_form,
        'site_name': 'City College of Bayawan',
    })


@login_required
def preferences_view(request):
    """Preferences for staff/faculty: language and email notifications only (no timezone)."""
    from django.contrib import messages
    user = request.user
    role = get_user_role(user)
    if role not in ('staff', 'faculty'):
        return redirect('profile-edit')
    profile, _ = StaffPersonnelProfile.objects.get_or_create(user=user, defaults={})
    form = UserPreferencesForm(initial={
        'preferred_language': profile.preferred_language or 'en',
        'email_notifications_announcements': profile.email_notifications_announcements,
    })
    if request.method == 'POST':
        form = UserPreferencesForm(request.POST)
        if form.is_valid():
            lang = (form.cleaned_data.get('preferred_language') or 'en')[:10]
            if lang not in ('en', 'fil'):
                lang = 'en'
            profile.preferred_language = lang
            profile.email_notifications_announcements = form.cleaned_data.get('email_notifications_announcements', True)
            profile.save(update_fields=['preferred_language', 'email_notifications_announcements'])
            from django.utils.translation import LANGUAGE_SESSION_KEY, activate, gettext as _
            request.session[LANGUAGE_SESSION_KEY] = lang
            request.session.modified = True
            activate(lang)
            messages.success(request, _('Preferences saved.'))
            return redirect('preferences')
    return render(request, 'users/preferences.html', {
        'form': form,
        'site_name': 'City College of Bayawan',
    })


def register_page(request):
    """Unified login and registration page."""
    from django.contrib import messages
    from django.contrib.auth.models import Group
    from gate.forms import StudentRegistrationForm
    from gate.models import StaffPersonnelProfile
    from .forms import LoginForm
    import random
    import string

    # Initialize forms
    login_form = LoginForm()
    reg_form = StudentRegistrationForm()
    staff_personnel_form = StaffPersonnelRegistrationForm()

    def _register_context(extra=None):
        ctx = {
            'form': login_form,
            'reg_form': reg_form,
            'staff_personnel_form': staff_personnel_form,
            'site_name': 'City College of Bayawan',
            'default_panel': 'register',
        }
        if extra:
            ctx.update(extra)
        return ctx

    if request.method == 'POST':
        # Staff / Faculty registration (separate form with registration_type=staff_personnel)
        if request.POST.get('registration_type') == 'staff_personnel':
            staff_personnel_form = StaffPersonnelRegistrationForm(request.POST)
            if staff_personnel_form.is_valid():
                from django.contrib.auth import get_user_model
                User = get_user_model()
                role = (staff_personnel_form.cleaned_data.get('role') or 'staff').lower()
                username = staff_personnel_form.cleaned_data['username']
                email = staff_personnel_form.cleaned_data['email']
                password = staff_personnel_form.cleaned_data['password']
                first_name = (staff_personnel_form.cleaned_data.get('first_name') or '').strip()
                last_name = (staff_personnel_form.cleaned_data.get('last_name') or '').strip()
                middle_name = (staff_personnel_form.cleaned_data.get('middle_name') or '').strip()
                user = User.objects.create_user(
                    username=username,
                    email=email,
                    password=password,
                    first_name=first_name,
                    last_name=last_name,
                    is_active=False,
                )
                group, _ = Group.objects.get_or_create(name=role)
                user.groups.add(group)
                StaffPersonnelProfile.objects.update_or_create(
                    user=user,
                    defaults={
                        'middle_name': middle_name,
                        'profile_complete': False,
                    },
                )
                from gate.admin_notification_service import AdminNotificationService
                role_display = {'staff': 'Staff', 'faculty': 'Faculty'}.get(role, role.title())
                AdminNotificationService.notify_staff_personnel_registration(user, role_display)
                messages.success(
                    request,
                    'Registration submitted. Your account is pending approval—you can sign in once an administrator activates it.'
                )
                return redirect('login')
            return render(request, 'auth/login.html', _register_context({'default_reg_type': 'staff_personnel'}))

        # Login form
        if 'username' in request.POST:  # Login form
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                username = login_form.cleaned_data['username']
                password = login_form.cleaned_data['password']
                user = authenticate(request, username=username, password=password)
                
                if user is not None:
                    login(request, user)
                    return redirect('dashboard')
                else:
                    login_form.add_error(None, 'Invalid username or password.')
        
        elif 'last_name' in request.POST:  # Registration form
            # Face registration on mobile sends base64 in POST; form expects a file. Inject photo into FILES before validation.
            reg_files = request.FILES
            face_base64_raw = (request.POST.get('face_photo_base64') or '').strip()
            if face_base64_raw:
                import base64
                from io import BytesIO
                from django.core.files.uploadedfile import InMemoryUploadedFile
                from django.utils.datastructures import MultiValueDict
                try:
                    face_base64 = face_base64_raw.split(',', 1)[1] if ',' in face_base64_raw else face_base64_raw
                    data = base64.b64decode(face_base64)
                    photo_file = InMemoryUploadedFile(
                        BytesIO(data), 'photo', 'face.jpg',
                        'image/jpeg', len(data), None
                    )
                    reg_files = MultiValueDict(request.FILES)
                    reg_files.setlist('photo', [photo_file])
                except Exception:
                    pass  # Let form validate; will show photo error if decode failed
            reg_form = StudentRegistrationForm(request.POST, reg_files)
            if reg_form.is_valid():
                student_id = (reg_form.cleaned_data.get('student_id') or '').strip()
                if not student_id:
                    while True:
                        candidate = 'REG-' + ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
                        if not Student.objects.filter(student_id=candidate).exists():
                            student_id = candidate
                            break
                else:
                    if Student.objects.filter(student_id=student_id).exists():
                        reg_form.add_error('student_id', 'This ID number is already registered.')
                        return render(request, 'auth/login.html', _register_context())

                import base64
                from io import BytesIO
                from django.core.files.uploadedfile import InMemoryUploadedFile

                photo = reg_form.cleaned_data.get('photo')
                face_base64 = (request.POST.get('face_photo_base64') or '').strip()
                if face_base64:
                    try:
                        if ',' in face_base64:
                            face_base64 = face_base64.split(',', 1)[1]
                        data = base64.b64decode(face_base64)
                        photo = InMemoryUploadedFile(
                            BytesIO(data), 'photo', 'face.jpg',
                            'image/jpeg', len(data), None
                        )
                    except Exception:
                        reg_form.add_error('photo', 'Invalid face image. Please complete face registration again.')
                        return render(request, 'auth/login.html', _register_context())
                if not photo:
                    reg_form.add_error('photo', 'Please complete face registration using your camera.')
                    return render(request, 'auth/login.html', _register_context())

                from django.core.exceptions import ValidationError
                from gate.forms import validate_student_photo
                from gate.utils import compress_student_photo
                try:
                    validate_student_photo(photo)
                except ValidationError as e:
                    msg = e.messages[0] if e.messages else str(e)
                    reg_form.add_error('photo', msg)
                    return render(request, 'auth/login.html', _register_context())
                if hasattr(photo, 'seek'):
                    photo.seek(0)
                photo = compress_student_photo(photo)

                try:
                    import face_recognition
                    img = face_recognition.load_image_file(photo)
                    locations = face_recognition.face_locations(img)
                    if not locations:
                        reg_form.add_error('photo', 'No face detected. Please upload a clear face photo.')
                        return render(request, 'auth/login.html', _register_context())
                    if len(locations) > 1:
                        reg_form.add_error('photo', 'Multiple faces detected. Please upload a photo with only one person.')
                        return render(request, 'auth/login.html', _register_context())
                except ImportError:
                    pass
                except Exception:
                    reg_form.add_error('photo', 'Could not process the image. Please upload a different photo.')
                    return render(request, 'auth/login.html', _register_context())

                if hasattr(photo, 'seek'):
                    photo.seek(0)

                # Electronic signature (required)
                signature_base64_raw = (request.POST.get('signature_base64') or '').strip()
                sig_file = None
                if signature_base64_raw:
                    import base64
                    from io import BytesIO
                    from django.core.files.uploadedfile import InMemoryUploadedFile
                    try:
                        signature_base64 = signature_base64_raw.split(',', 1)[1] if ',' in signature_base64_raw else signature_base64_raw
                        data = base64.b64decode(signature_base64)
                        if len(data) < 100:
                            raise ValueError('Signature too small')
                        sig_file = InMemoryUploadedFile(
                            BytesIO(data), 'signature', 'signature.png',
                            'image/png', len(data), None
                        )
                    except Exception:
                        sig_file = None
                if not sig_file:
                    reg_form.add_error(None, 'Please provide your electronic signature by drawing in the signature box.')
                    return render(request, 'auth/login.html', _register_context())

                email = (reg_form.cleaned_data.get('email') or '').strip().lower()
                if Student.objects.filter(email__iexact=email).exists():
                    reg_form.add_error('email', 'This email address is already registered.')
                    return render(request, 'auth/login.html', _register_context())

                first_name = (reg_form.cleaned_data.get('first_name') or '').strip()
                middle_name = (reg_form.cleaned_data.get('middle_name') or '').strip()
                last_name = (reg_form.cleaned_data.get('last_name') or '').strip()
                sex = (reg_form.cleaned_data.get('sex') or '').strip()

                Student.objects.create(
                    student_id=student_id,
                    first_name=first_name,
                    middle_name=middle_name,
                    last_name=last_name,
                    email=email,
                    photo=photo,
                    signature=sig_file,
                    address=(reg_form.cleaned_data.get('address') or '').strip(),
                    birthdate=reg_form.cleaned_data.get('birthdate'),
                    sex=sex or '',
                    guardians_parents=(reg_form.cleaned_data.get('guardians_parents') or '').strip(),
                    account_status=Student.ACCOUNT_STATUS_PENDING,
                    is_active=False,
                    course=(reg_form.cleaned_data.get('course') or '').strip() or None,
                    year_level=(reg_form.cleaned_data.get('year_level') or '').strip() or None,
                    section=(reg_form.cleaned_data.get('section') or '').strip() or None,
                    contact_number=(reg_form.cleaned_data.get('contact_number') or '').strip() or None,
                    guardian_contact=(reg_form.cleaned_data.get('guardian_contact') or '').strip() or None,
                )
                messages.success(
                    request,
                    f'Registration submitted. Pending administrator approval. (Ref: {student_id})'
                )
                return redirect('login')

    return render(request, 'auth/login.html', _register_context())

def logout_page(request):
    logout(request)
    return redirect('login')