# Generated by Django 2.2.28 on 2026-01-30 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_auto_20200724_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GateIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_id', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(choices=[('identity_mismatch', 'Identity Mismatch'), ('invalid_id', 'Invalid or Expired ID'), ('not_registered', 'Not Registered'), ('other', 'Other')], default='identity_mismatch', max_length=30)),
                ('details', models.TextField(blank=True)),
                ('guard_alerted', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.Student')),
            ],
        ),
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entry', to='gate.GateIncident')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate.Student')),
            ],
            options={
                'verbose_name_plural': 'Gate entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate.Event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate.Student')),
            ],
            options={
                'verbose_name_plural': 'Event attendances',
                'ordering': ['-recorded_at'],
                'unique_together': {('student', 'event')},
            },
        ),
    ]
