# Generated by Django 2.2.28 on 2026-02-03 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0004_create_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateentry',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Guard/user who recorded this entry (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entries_recorded', to=settings.AUTH_USER_MODEL),
        ),
    ]
