# Generated by Django 2.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0005_add_gate_entry_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateentry',
            name='out_reason',
            field=models.TextField(
                blank=True,
                help_text='Reason for early/forced out when guard records OUT on a duplicate scan (used in reports).'
            ),
        ),
    ]
