# Generated by Django 2.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0006_gateentry_out_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_category/'),
        ),
    ]
