# Generated by Django 2.2.28 on 2026-02-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0007_eventcategory_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardians_parents',
            field=models.CharField(blank=True, help_text='Guardian(s) or parent(s) name(s)', max_length=255),
        ),
        migrations.AlterField(
            model_name='gateincident',
            name='reason',
            field=models.CharField(choices=[('identity_mismatch', 'Identity Mismatch'), ('invalid_id', 'Invalid or Expired ID'), ('not_registered', 'Not Registered'), ('proxy_attendance', 'Proxy Attendance'), ('other', 'Other')], default='identity_mismatch', max_length=30),
        ),
    ]
