# Generated by Django 2.2.28 on 2026-02-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0008_add_student_address_birthdate_guardians'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
