# Generated by Django 2.2.28 on 2026-02-16 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0011_gateentry_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique token for QR code: EVT:<event_id>:<token>', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='When student scanned IN at event', null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, help_text='When student scanned OUT at event', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='gate.Event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='gate.Student')),
            ],
            options={
                'verbose_name_plural': 'Event registrations',
                'ordering': ['-issued_at'],
                'unique_together': {('event', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True, help_text='Server time when scan was recorded')),
                ('client_scan_time', models.DateTimeField(blank=True, help_text='Client device time (for offline scans)', null=True)),
                ('scan_type', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out')], default='IN', max_length=3)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('DUPLICATE', 'Duplicate Scan'), ('INVALID', 'Invalid Token'), ('REVOKED', 'Token Revoked'), ('WRONG_EVENT', 'Wrong Event'), ('OUTSIDE_WINDOW', 'Outside Time Window'), ('NOT_CHECKED_IN', 'Check-out Before Check-in')], max_length=20)),
                ('token', models.CharField(blank=True, default='', help_text='Token that was scanned', max_length=64)),
                ('device_id', models.CharField(blank=True, default='', help_text='Scanner device identifier', max_length=64)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='gate.Event')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='gate.EventRegistration')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='gate.Student')),
            ],
            options={
                'verbose_name_plural': 'Attendance logs',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['event', 'result', '-scan_time'], name='events_atte_event_i_5ed18d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['student', '-scan_time'], name='events_atte_student_7f3c10_idx'),
        ),
    ]
