# Generated by Django 2.2.28 on 2026-02-16 01:08
# Adjusted for MySQL: do not drop indexes that back FK constraints; only add new ones.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0012_add_event_registration_and_attendance_log'),
    ]

    operations = [
        # Skip RemoveIndex on MySQL (index backs FK). New indexes added below.
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['event', 'result', 'scan_time'], name='gate_atte_event_i_9fdc16_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['student', 'scan_time'], name='gate_atte_student_450e41_idx'),
        ),
    ]
