# Generated by Django 2.2.28 on 2026-02-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0013_add_checkin_checkout_to_event_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='When student checked in at event', null=True),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='When student checked out from event', null=True),
        ),
    ]
