# Generated by Django 2.2.28 on 2026-02-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0014_auto_20260216_0909'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['event', 'student'], name='gate_even_event_i_4db0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['event', 'checked_in_at'], name='gate_even_event_i_948f77_idx'),
        ),
    ]
