# Generated by Django 2.2.28 on 2026-02-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0015_add_eventattendance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='UUID from scanner (localStorage scanner_device_id)', max_length=128, unique=True)),
                ('name', models.CharField(blank=True, help_text='Friendly name, e.g. "Gate A Tablet"', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Physical location, e.g. "Main Gate"', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Scanner device',
                'verbose_name_plural': 'Scanner devices',
                'ordering': ['name', 'device_id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='attendance_mode',
            field=models.CharField(choices=[('OPEN', 'Open (Student QR accepted)'), ('SECURE', 'Secure (Token QR required)')], default='OPEN', help_text='OPEN: any student QR works. SECURE: only pre-registered token QR accepted.', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='result',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('DUPLICATE', 'Duplicate Scan'), ('INVALID', 'Invalid Token'), ('REVOKED', 'Token Revoked'), ('WRONG_EVENT', 'Wrong Event'), ('OUTSIDE_WINDOW', 'Outside Time Window'), ('NOT_CHECKED_IN', 'Check-out Before Check-in'), ('SECURE_EVENT_REQUIRES_TOKEN', 'Secure Event (Token Required)')], max_length=20),
        ),
    ]
