# Generated by Django 2.2.28 on 2026-02-16 02:21

from django.db import migrations, models


def migrate_event_status(apps, schema_editor):
    """Map old status values to new: cancel->cancelled, disabled/deleted->archived, time out->completed."""
    Event = apps.get_model('gate', 'Event')
    mapping = {
        'cancel': 'cancelled',
        'disabled': 'draft',
        'deleted': 'archived',
        'time out': 'completed',
    }
    for old, new in mapping.items():
        Event.objects.filter(status=old).update(status=new)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0016_attendance_mode_and_scanner_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='scheduled_status',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (not scheduled)'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='uid',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-generated if blank', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(migrate_event_status, noop),
    ]
