# Generated by Django 2.2.28 on 2026-02-16 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0017_event_datetime_status_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Staff/guard who recorded this scan (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='voided',
            field=models.BooleanField(default=False, help_text='If True, this log entry was voided/corrected by admin.'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='voided_by',
            field=models.ForeignKey(blank=True, help_text='Admin who voided this log.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs_voided', to=settings.AUTH_USER_MODEL),
        ),
    ]
