# Generated by Django 2.2.28 on 2026-02-19 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0018_attendance_log_recorded_by_and_voided'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_or_section',
            field=models.CharField(blank=True, default='', help_text='e.g. BSIT-A, BSCS (for reports by course/section)', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.CharField(blank=True, default='', help_text='e.g. 1st Year, 2nd Year (for reports by year level)', max_length=50),
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('on_demand', 'On-demand')], max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, help_text='JSON: summary stats (counts, peak hours, etc.)')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated report',
                'verbose_name_plural': 'Generated reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
