# Generated by Django 2.2.28 on 2026-02-19 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0019_student_report_fields_and_generated_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='City College of Bayawan', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='theme/')),
                ('primary_color', models.CharField(default='#28a745', help_text='Hex color e.g. #28a745', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site theme',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='capacity_alert_sent_at',
            field=models.DateTimeField(blank=True, help_text='When 80%% capacity alert was last sent', null=True),
        ),
        migrations.AddField(
            model_name='gateincident',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo attached by guard', null=True, upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_or_section',
            field=models.CharField(blank=True, help_text='e.g. BSIT-A, BSCS (for reports by course/section)', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(blank=True, help_text='e.g. 1st Year, 2nd Year (for reports by year level)', max_length=50),
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='QR payload or code', max_length=64, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visitor passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('block_from', models.DateField()),
                ('block_until', models.DateField()),
                ('is_allowlist', models.BooleanField(default=False, help_text='If True, only allow access in this window; else block.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_blocks', to='gate.Student')),
            ],
            options={
                'verbose_name_plural': 'Student blocks',
                'ordering': ['-block_from'],
            },
        ),
        migrations.CreateModel(
            name='RecurringEventTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('recurrence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0=Monday, 6=Sunday (for weekly)', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-31 (for monthly)', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recurring event templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. void_log, mark_present, deactivate_student', max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventWaitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, help_text='When moved from waitlist to registration', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='gate.Event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_waitlist_entries', to='gate.Student')),
            ],
            options={
                'verbose_name_plural': 'Event waitlists',
                'ordering': ['event', 'position'],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
