# Generated by Django 2.2.28 on 2026-02-20 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gate.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0020_extended_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=gate.models.student_photo_upload_to),
        ),
        migrations.CreateModel(
            name='VisitorEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(help_text='Full name of the visitor', max_length=200)),
                ('purpose', models.CharField(help_text='Purpose of visit (e.g. meeting, delivery)', max_length=255)),
                ('who_to_visit', models.CharField(help_text='Person, office, or department they are visiting', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(help_text='Guard who recorded this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visitor entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
