# Generated by Django 2.2.28 on 2026-02-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0022_student_account_status_and_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('BST', 'BST'), ('BSE', 'BSE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_or_section',
            field=models.CharField(blank=True, help_text='Legacy: e.g. BSIT-A (for reports).', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentLoadSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='e.g. 2025-2026', max_length=9)),
                ('semester', models.CharField(choices=[('1st', '1st Sem'), ('2nd', '2nd Sem'), ('summer', 'Summer')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_slips', to='gate.Student')),
            ],
            options={
                'ordering': ['-school_year', 'semester'],
                'unique_together': {('student', 'school_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='LoadSlipSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_title', models.CharField(max_length=150)),
                ('section', models.CharField(max_length=30)),
                ('units', models.DecimalField(decimal_places=1, default=3.0, max_digits=4)),
                ('day', models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('load_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='gate.StudentLoadSlip')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
