# Generated by Django 2.2.28 on 2026-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0023_load_slip_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadslipsubject',
            name='schedule',
            field=models.CharField(blank=True, help_text='e.g. TTH/ 10:00-11:30 AM (optional)', max_length=120),
        ),
    ]
