# Generated by Django 2.2.28 on 2026-02-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0024_add_loadslipsubject_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpass',
            name='department',
            field=models.CharField(blank=True, help_text='Department/office the visitor is going to', max_length=255),
        ),
    ]
