# Generated by Django 2.2.28 on 2026-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0025_add_visitor_pass_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(choices=[('on_campus', 'On campus (gate scan)'), ('field_trip', 'Field trip / Off-campus')], default='on_campus', help_text='On campus: use gate scan with "Tracking event". Field trip: use event attendance scan (no gate entry).', max_length=20),
        ),
    ]
