# Generated by Django 2.2.28 on 2026-02-23 00:41
# Adjusted for MySQL: do not drop indexes that back FK constraints; only add new ones.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0026_add_event_location_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['event', 'result', 'scan_time'], name='gate_attend_event_i_8ec9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['student', 'scan_time'], name='gate_attend_student_cf45bd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['event', 'student'], name='gate_eventa_event_i_60410e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['event', 'checked_in_at'], name='gate_eventa_event_i_599e61_idx'),
        ),
    ]
