# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0027_index_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorentry',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional face capture as proof of visitor at entry.', null=True, upload_to='visitor_photos/%Y/%m/'),
        ),
    ]
