# Generated by Django 2.2.28 on 2026-02-24 00:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


def create_default_policy(apps, schema_editor):
    GatePolicy = apps.get_model('gate', 'GatePolicy')
    if not GatePolicy.objects.exists():
        GatePolicy.objects.create(
            name='Default',
            gate_open_time=datetime.time(7, 0),
            lunch_out_start=datetime.time(11, 59),
            lunch_in_start=datetime.time(12, 59),
            general_out_until=datetime.time(17, 0),
            strict_lunch_return=True,
            out_buffer_minutes=30,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0035_add_gateentry_scan_type_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='e.g. Default, Main Gate', max_length=80)),
                ('gate_open_time', models.TimeField(default=datetime.time(7, 0), help_text='Gate opens for entry (e.g. 07:00)')),
                ('lunch_out_start', models.TimeField(default=datetime.time(11, 59), help_text='Lunch OUT allowed from (11:59)')),
                ('lunch_in_start', models.TimeField(default=datetime.time(12, 59), help_text='Lunch IN allowed from (12:59)')),
                ('general_out_until', models.TimeField(default=datetime.time(17, 0), help_text='General OUT allowed until (17:00); after this use last class end')),
                ('strict_lunch_return', models.BooleanField(default=True, help_text='If True, deny IN during 11:59–12:59')),
                ('out_buffer_minutes', models.PositiveSmallIntegerField(default=30, help_text='Deny OUT if class starts within this many minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gate policies',
            },
        ),
        migrations.AddField(
            model_name='gateentry',
            name='out_reason_code',
            field=models.CharField(blank=True, db_index=True, help_text='Short code for analytics: LUNCH, NO_CLASS_WINDOW, OVERRIDE_BY_GUARD, etc.', max_length=32),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional: if this scan is for tracking a specific college event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entries', to='gate.Event'),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='out_reason',
            field=models.TextField(blank=True, help_text='Reason for early/forced out when guard records OUT (used in reports).'),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Null when result=NOT_FOUND.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gate.Student'),
        ),
        migrations.RunPython(create_default_policy, migrations.RunPython.noop),
    ]
