# Generated by Django 2.2.28 on 2026-02-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0038_reusable_visitor_pass_and_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maximum_attende',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Null when result=NOT_FOUND or visitor.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gate.Student'),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='visitor_visit',
            field=models.ForeignKey(blank=True, help_text='When set, this entry is visitor check-in/out (reusable pass lifecycle).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entries', to='gate.VisitorVisit'),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='code',
            field=models.CharField(db_index=True, help_text='QR payload e.g. VIS-001 or VISITOR-xxx', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='current_visit',
            field=models.OneToOneField(blank=True, help_text='Active visit when status=IN_USE; null after check-out', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_current_for', to='gate.VisitorVisit'),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='department',
            field=models.CharField(blank=True, help_text='Department/office (legacy or default for reusable)', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Legacy one-time pass: guest name; blank for reusable', max_length=200),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Last check-out time (reusable passes)', null=True),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Legacy one-time: when consumed', null=True),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Legacy one-time: valid window start', null=True),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Legacy one-time: valid window end', null=True),
        ),
        migrations.AlterField(
            model_name='visitorvisit',
            name='department',
            field=models.CharField(blank=True, help_text='Department/office visiting', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitorvisit',
            name='id_type',
            field=models.CharField(blank=True, help_text='e.g. Government ID, Company ID', max_length=80),
        ),
        migrations.AlterField(
            model_name='visitorvisit',
            name='pass_obj',
            field=models.ForeignKey(help_text='Reusable pass used for this visit', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gate.VisitorPass'),
        ),
    ]
