# Generated by Django 2.2.28 on 2026-02-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0039_event_optional_venue_points_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateincident',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='gateincident',
            index=models.Index(fields=['timestamp'], name='gate_gatein_timesta_c34a79_idx'),
        ),
    ]
