# Generated by Django 2.2.28 on 2026-02-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0040_gate_incident_timestamp_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gateentry',
            index=models.Index(fields=['granted', 'timestamp'], name='gate_gateen_granted_9f7945_idx'),
        ),
    ]
