# Generated by Django 2.2.28 on 2026-03-03 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0042_student_add_sex_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateentry',
            options={'ordering': ['-timestamp'], 'permissions': [('can_scan', 'Can scan at gate (IN/OUT)'), ('can_view_entries', 'Can view gate entries'), ('can_record_early_out', 'Can record early out / override'), ('can_report_proxy', 'Can report proxy attendance')], 'verbose_name_plural': 'Gate entries'},
        ),
        migrations.AddField(
            model_name='gateentry',
            name='device_id',
            field=models.CharField(blank=True, default='', help_text='Scanner/terminal device ID (browser UUID from gate scan).', max_length=128),
        ),
        migrations.AddField(
            model_name='gateentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP when entry was recorded (audit).', null=True),
        ),
        migrations.CreateModel(
            name='GuardShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField(help_text='Clock-in time.')),
                ('shift_end', models.DateTimeField(blank=True, help_text='Clock-out time; null = still on duty.', null=True)),
                ('gate_post', models.CharField(blank=True, default='', help_text='E.g. Main Gate, Back Gate (optional).', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('guard', models.ForeignKey(help_text='Guard user (should be in Guard group).', on_delete=django.db.models.deletion.CASCADE, related_name='guard_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guard shift',
                'verbose_name_plural': 'Guard shifts',
                'ordering': ['-shift_start'],
            },
        ),
        migrations.AddIndex(
            model_name='guardshift',
            index=models.Index(fields=['guard', '-shift_start'], name='gate_guards_guard_i_38848e_idx'),
        ),
        migrations.AddIndex(
            model_name='guardshift',
            index=models.Index(fields=['shift_start', 'shift_end'], name='gate_guards_shift_s_2a41f1_idx'),
        ),
    ]
