# Generated by Django 2.2.28 on 2026-03-04 09:38

from django.db import migrations, models
import gate.models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0044_assign_guard_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, help_text='Electronic signature from registration.', null=True, upload_to=gate.models.student_signature_upload_to),
        ),
    ]
