# Generated by Django 2.2.28 on 2026-03-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0047_event_audience_targeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendance_mode',
            field=models.CharField(choices=[('OPEN', 'Open (Student eEID accepted)'), ('SECURE', 'Secure (legacy token option; student eEID still works)')], default='OPEN', help_text='Attendance is taken by scanning student eEID at Events → Attendance Scanner. OPEN is recommended.', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(choices=[('on_campus', 'On campus'), ('field_trip', 'Field trip / Off-campus')], default='on_campus', help_text='Display only. Attendance for both types is taken via Events → Attendance Scanner (student eEID).', max_length=20),
        ),
    ]
