# Generated by Django 2.2.28 on 2026-03-05 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0048_auto_20260305_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guard', models.ForeignKey(help_text='Guard who created this note', on_delete=django.db.models.deletion.CASCADE, related_name='guard_notes_created', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, help_text='Shift during which this note was created (null if created outside shift)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_notes', to='gate.GuardShift')),
            ],
            options={
                'verbose_name_plural': 'Guard notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('incident', 'Incident Alert'), ('capacity', 'Capacity Alert'), ('shift_reminder', 'Shift Reminder'), ('suspicious', 'Suspicious Activity'), ('system', 'System Message')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('broadcast', models.BooleanField(default=False, help_text='Send to all on-duty guards')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expires after this time', null=True)),
                ('related_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.GateEntry')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.Event')),
                ('related_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.GateIncident')),
                ('target_guard', models.ForeignKey(blank=True, help_text='Specific guard to notify (null if broadcast)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Guard notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardNoteRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_read', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='gate.GuardNote')),
            ],
            options={
                'verbose_name_plural': 'Guard note reads',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('scan', 'Gate Scan'), ('override', 'Override Decision'), ('incident', 'Incident Report'), ('shift_start', 'Shift Clock In'), ('shift_end', 'Shift Clock Out'), ('note', 'Note Created'), ('visitor_checkin', 'Visitor Check-in'), ('visitor_checkout', 'Visitor Check-out'), ('early_out', 'Early Out Recorded'), ('lookup', 'Student Lookup')], db_index=True, max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('device_id', models.CharField(blank=True, help_text='Scanner device ID', max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('metadata', models.TextField(blank=True, help_text='Additional context (JSON format)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guard', models.ForeignKey(help_text='Guard who performed this action', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('related_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.GateEntry')),
                ('related_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.GateIncident')),
                ('related_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.GuardShift')),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.Student')),
            ],
            options={
                'verbose_name_plural': 'Guard activity logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='guardnotification',
            index=models.Index(fields=['target_guard', 'is_read', '-created_at'], name='gate_guardn_target__f3c32b_idx'),
        ),
        migrations.AddIndex(
            model_name='guardnotification',
            index=models.Index(fields=['notification_type', '-created_at'], name='gate_guardn_notific_c80d35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guardnoteread',
            unique_together={('note', 'guard')},
        ),
        migrations.AddIndex(
            model_name='guardactivitylog',
            index=models.Index(fields=['guard', '-timestamp'], name='gate_guarda_guard_i_7cbaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='guardactivitylog',
            index=models.Index(fields=['action_type', '-timestamp'], name='gate_guarda_action__8da3dd_idx'),
        ),
    ]
