# Generated by Django 2.2.28 on 2026-03-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0050_auto_20260306_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='early_out_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for leaving event early', max_length=500),
        ),
    ]
