# Generated by Django 2.2.28 on 2026-03-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0051_eventattendance_early_out_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='default_first_signatory_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='default_first_signatory_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='default_second_signatory_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='default_second_signatory_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience_course',
            field=models.CharField(blank=True, default='', help_text='Required when audience is by course / course+year / course+section / course+section+year.', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience_scope',
            field=models.CharField(choices=[('all', 'All students'), ('course', 'By course'), ('year_level', 'By year level'), ('course_year', 'By course + year level'), ('course_section', 'By course + section'), ('course_section_year', 'By course + section + year level'), ('specific_students', 'Specific students (registration list)')], default='all', help_text='Target audience for this event. Scanner checks student eligibility based on this rule.', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience_section',
            field=models.CharField(blank=True, default='', help_text='Required when audience is by course+section / course+section+year.', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience_year_level',
            field=models.CharField(blank=True, default='', help_text='Required when audience is by year level / course+year / course+section+year.', max_length=10),
        ),
    ]
