# Generated by Django 2.2.28 on 2026-03-12 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0053_add_blockedip_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffFacultyGuardProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('faculty', 'Faculty'), ('guard', 'Guard')], max_length=20)),
                ('employee_id', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_faculty_guard_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff/Faculty/Guard profile',
                'verbose_name_plural': 'Staff/Faculty/Guard profiles',
            },
        ),
    ]
