# Generated by Django 2.2.28 on 2026-03-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0054_add_staff_faculty_guard_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffacultyguardprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stafffacultyguardprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafffacultyguardprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='stafffacultyguardprofile',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
