# Generated by Django 2.2.28 on 2026-03-13 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gate.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0056_add_staff_guard_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('student_registration', 'Student Registration'), ('staff_guard_registration', 'Staff/Faculty/Guard Registration'), ('incident', 'Incident Alert'), ('capacity', 'Capacity Alert'), ('system', 'System Message'), ('guard_alert', 'Guard Alert')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Profile photo shown in the sidebar.', null=True, upload_to=gate.models.user_profile_photo_upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
