# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0057_add_user_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffguardprofile',
            name='profile_complete',
            field=models.BooleanField(default=False, help_text='True after staff/guard completes the required profile form after first login.'),
        ),
    ]
