# Generated by Django — one-time: users in "Guard" group are moved to "Staff" (guard role removed).

from django.db import migrations


def migrate_guard_users_to_staff(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    guard = Group.objects.filter(name__iexact='guard').first()
    staff = Group.objects.filter(name__iexact='staff').first()
    if not guard or not staff:
        return
    for user in User.objects.filter(groups=guard).iterator():
        user.groups.add(staff)
        user.groups.remove(guard)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0061_gatepolicy_require_load_slip_for_entry'),
    ]

    operations = [
        migrations.RunPython(migrate_guard_users_to_staff, noop_reverse),
    ]
