# Generated by Django 2.2.28 on 2026-03-20 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0063_remove_guard_group_if_empty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardactivitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Gate activity log', 'verbose_name_plural': 'Gate activity logs'},
        ),
        migrations.AlterModelOptions(
            name='guardnote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gate handover note', 'verbose_name_plural': 'Gate handover notes'},
        ),
        migrations.AlterModelOptions(
            name='guardnoteread',
            options={'ordering': ['-read_at'], 'verbose_name': 'Gate note read', 'verbose_name_plural': 'Gate note reads'},
        ),
        migrations.AlterModelOptions(
            name='guardnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gate notification', 'verbose_name_plural': 'Gate notifications'},
        ),
        migrations.AlterModelOptions(
            name='guardshift',
            options={'ordering': ['-shift_start'], 'verbose_name': 'Gate shift', 'verbose_name_plural': 'Gate shifts'},
        ),
        migrations.AlterModelOptions(
            name='staffguardprofile',
            options={'verbose_name': 'Staff/Faculty/Personnel profile', 'verbose_name_plural': 'Staff/Faculty/Personnel profiles'},
        ),
        migrations.AddField(
            model_name='gatepolicy',
            name='permissive_college_mode',
            field=models.BooleanField(default=False, help_text='If True, allow IN/OUT without schedule/time blocks (no “no class today”, gate hours, or reason prompts). Still blocks duplicate IN when already inside and duplicate OUT when already outside. Optional “require load slip” above still applies.'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('student_registration', 'Student Registration'), ('staff_guard_registration', 'Staff/Faculty/Personnel Registration'), ('incident', 'Incident Alert'), ('capacity', 'Capacity Alert'), ('system', 'System Message'), ('guard_alert', 'Personnel alert')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who recorded this scan (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='out_reason',
            field=models.TextField(blank=True, help_text='Reason for early/forced out when staff records OUT (used in reports).'),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who recorded this entry (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_entries_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gateincident',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo attached by gate staff', null=True, upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='guardactivitylog',
            name='guard',
            field=models.ForeignKey(help_text='User who performed this action', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardnote',
            name='guard',
            field=models.ForeignKey(help_text='User who created this note', on_delete=django.db.models.deletion.CASCADE, related_name='guard_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardnotification',
            name='broadcast',
            field=models.BooleanField(default=False, help_text='Send to all on-duty personnel'),
        ),
        migrations.AlterField(
            model_name='guardnotification',
            name='target_guard',
            field=models.ForeignKey(blank=True, help_text='Specific user to notify (null if broadcast)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardshift',
            name='guard',
            field=models.ForeignKey(help_text='Personnel user on duty for this shift.', on_delete=django.db.models.deletion.CASCADE, related_name='guard_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffguardprofile',
            name='profile_complete',
            field=models.BooleanField(default=False, help_text='True after staff completes the required profile form after first login.'),
        ),
        migrations.AlterField(
            model_name='visitorentry',
            name='recorded_by',
            field=models.ForeignKey(help_text='Staff user who recorded this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries_recorded', to=settings.AUTH_USER_MODEL),
        ),
    ]
