# Generated by Django 2.2.28 on 2026-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0064_gatepolicy_permissive_college_mode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentloadslip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentloadslip',
            name='student',
        ),
        migrations.RemoveField(
            model_name='gatepolicy',
            name='require_load_slip_for_entry',
        ),
        migrations.AlterField(
            model_name='gatepolicy',
            name='out_buffer_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Legacy: was used with class-based OUT rules.'),
        ),
        migrations.AlterField(
            model_name='gatepolicy',
            name='permissive_college_mode',
            field=models.BooleanField(default=True, help_text='Legacy toggle. Daily gate now always uses college-style IN/OUT (no class schedule).'),
        ),
        migrations.DeleteModel(
            name='LoadSlipSubject',
        ),
        migrations.DeleteModel(
            name='StudentLoadSlip',
        ),
    ]
