# Generated by Django 2.2.28 on 2026-03-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0068_refresh_gate_permission_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin notification', 'verbose_name_plural': 'Admin notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationread',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification read', 'verbose_name_plural': 'Notification reads'},
        ),
    ]
