# Generated by Django 2.2.28 on 2026-03-20 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0069_notification_admin_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateincident',
            name='guard_alerted',
            field=models.BooleanField(default=True, help_text='Whether gate personnel were notified about this incident.', verbose_name='Gate staff alerted'),
        ),
        migrations.AlterField(
            model_name='guardactivitylog',
            name='guard',
            field=models.ForeignKey(help_text='User who performed this action.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Performed by'),
        ),
        migrations.AlterField(
            model_name='guardnote',
            name='guard',
            field=models.ForeignKey(help_text='User who created this note.', on_delete=django.db.models.deletion.CASCADE, related_name='guard_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='guardnoteread',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_read', to=settings.AUTH_USER_MODEL, verbose_name='Reader'),
        ),
        migrations.AlterField(
            model_name='guardnotification',
            name='target_guard',
            field=models.ForeignKey(blank=True, help_text='Specific user to notify (null if broadcast).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Notify user'),
        ),
        migrations.AlterField(
            model_name='guardshift',
            name='guard',
            field=models.ForeignKey(help_text='Personnel user on duty for this shift.', on_delete=django.db.models.deletion.CASCADE, related_name='guard_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Personnel on duty'),
        ),
    ]
