# Generated by Django 2.2.28 on 2026-03-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0073_gate_personnel_fk_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='maximum_attende',
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='early_out_reason',
            field=models.TextField(blank=True, default='', help_text='Optional note when leaving the event before it ends', max_length=500),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='out_reason',
            field=models.TextField(blank=True, help_text='Optional note when staff records OUT (e.g. override, lunch). Used in reports.', verbose_name='OUT note'),
        ),
    ]
