# Generated by Django 2.2.28 on 2026-03-25 02:10

from django.db import migrations, models


def convert_old_statuses(apps, schema_editor):
    Student = apps.get_model('gate', 'Student')
    Student.objects.filter(account_status='REJECTED').update(account_status='INACTIVE', is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0074_remove_maximum_attende'),
    ]

    operations = [
        migrations.RunPython(convert_old_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
