# Generated by Django 3.2.25 on 2026-03-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0088_remove_supervisor_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('student_registration', 'Student Registration'), ('staff_personnel_registration', 'Staff/Faculty/Personnel Registration'), ('incident', 'Incident Alert'), ('sas_inactive_ready_activation', 'SAS checked — inactive student ready to activate'), ('capacity', 'Capacity Alert'), ('system', 'System Message'), ('personnel_alert', 'Personnel alert')], db_index=True, max_length=30),
        ),
    ]
