# Generated by Django 3.2.25 on 2026-04-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0093_remove_report_second_signatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('student_registration', 'Student registration'), ('staff_personnel_registration', 'Staff / faculty signup'), ('incident', 'Gate incident'), ('sas_inactive_ready_activation', 'SAS verified — needs activation'), ('sas_verified_gate_followup', 'SAS verified — no action'), ('gate_manual_referral', 'Guard manual — office route'), ('capacity', 'Capacity'), ('system', 'System'), ('personnel_alert', 'Personnel')], db_index=True, max_length=30),
        ),
    ]
