"""Gate Access & Attendance - City College of Bayawan."""
from django.urls import path
from . import gate_views
from . import gate_personnel_views

urlpatterns = [
    path('', gate_views.gate_scan, name='gate-scan'),
    path('guard-display/', gate_views.guard_scanner_dashboard, name='gate-guard-display'),
    path('embed-scanner/', gate_views.gate_scan_guard_embed, name='gate-embed-scanner'),
    path('sw.js', gate_views.gate_scan_sw, name='gate-scan-sw'),
    path('save-scan/', gate_views.save_scan, name='save_scan'),
    path('scan-event/', gate_views.scan_event_qr, name='scan_event_qr'),
    path('record-early-out/', gate_views.record_early_out, name='record_early_out'),
    path('visitor-checkin/', gate_views.visitor_checkin_submit, name='visitor-checkin-submit'),
    path('visitor-checkout/', gate_views.visitor_checkout_submit, name='visitor-checkout-submit'),
    path('visitor-force-checkout/', gate_views.visitor_force_checkout, name='visitor-force-checkout'),
    path('visitor-disable-pass/', gate_views.visitor_disable_pass, name='visitor-disable-pass'),
    path('record-visitor/', gate_views.record_visitor_entry, name='gate-record-visitor'),
    path('register-student/', gate_views.register_student_from_scan, name='gate-register-student'),
    path('lookup/', gate_views.lookup_student, name='gate-lookup'),
    path('record/', gate_views.record_entry, name='gate-record'),
    path('mark-participation/', gate_views.mark_participation, name='gate-mark-participation'),
    path('analytics/', gate_views.analytics_dashboard, name='gate-analytics'),
    path('analytics/profile-entries/', gate_views.analytics_profile_entries_json, name='gate-analytics-profile-entries'),
    path('analytics/report/', gate_views.analytics_report, name='gate-analytics-report'),
    path('students/', gate_views.student_list, name='gate-student-list'),
    path('users/pending-staff-personnel/', gate_views.pending_staff_personnel_list, name='pending-staff-personnel-list'),
    path('users/staff-personnel/export-csv/', gate_views.staff_personnel_export_csv, name='gate-staff-personnel-export-csv'),
    path('users/staff-personnel/import-csv/', gate_views.import_staff_personnel_csv, name='gate-staff-personnel-import-csv'),
    path('users/staff-personnel/create/', gate_views.staff_personnel_create, name='gate-staff-personnel-create'),
    path('users/staff-personnel/create/done/', gate_views.staff_personnel_create_modal_done, name='gate-staff-personnel-create-modal-done'),
    path('users/staff-personnel/eid/print-all/', gate_views.staff_personnel_eid_print_all, name='gate-staff-personnel-eid-print-all'),
    path('users/staff-personnel/<int:user_id>/eid/', gate_views.staff_personnel_eid_card, name='gate-staff-personnel-eid'),
    path('students/approve-all-pending/', gate_views.approve_all_pending_students, name='gate-student-approve-all-pending'),
    path('students/export-csv/', gate_views.student_list_export_csv, name='gate-student-export-csv'),
    path('students/import-csv/', gate_views.import_students_csv, name='gate-student-import'),
    path('students/sample-50.csv', gate_views.student_sample_csv, name='gate-student-sample-csv'),
    path('students/create/', gate_views.student_create, name='gate-student-create'),
    path('students/create/done/', gate_views.student_create_modal_done, name='gate-student-create-modal-done'),
    path('students/<int:pk>/edit/', gate_views.student_edit, name='gate-student-edit'),
    path('students/<int:pk>/qr/', gate_views.student_qr_image, name='gate-student-qr'),
    path('students/<int:pk>/eid/', gate_views.student_eid_card, name='gate-student-eid'),
    path('students/eid/print-all/', gate_views.student_eid_print_all, name='gate-student-eid-print-all'),
    path('entries/', gate_views.entry_list, name='gate-entry-list'),
    path('entries/event-attendees/', gate_views.event_attendees_embed, name='gate-event-attendees-embed'),
    path('visitors/', gate_views.visitor_entry_list, name='gate-visitor-list'),
    path('visitors/yearly/', gate_views.visitor_yearly_summary, name='gate-visitor-yearly'),
    path('entries/students/yearly/', gate_views.student_entries_yearly_summary, name='gate-student-entries-yearly'),
    path('incidents/', gate_views.incident_list, name='gate-incident-list'),
    path('incidents/<int:incident_id>/sas-verify/', gate_views.incident_sas_verify, name='gate-incident-sas-verify'),
    # Event attendance (token-based QR)
    path('events/attendance-scanner/', gate_views.event_attendance_scanner, name='event-attendance-scanner'),
    path('events/<int:event_id>/registrations/', gate_views.event_manage_registrations, name='event-manage-registrations'),
    path('events/<int:event_id>/registrations/export-csv/', gate_views.event_registrations_export_csv, name='event-registrations-export-csv'),
    path('events/<int:event_id>/attendance-report/', gate_views.event_attendance_report, name='event-attendance-report'),
    path('events/<int:event_id>/attendance-report/export-csv/', gate_views.event_attendance_report_export_csv, name='event-attendance-report-export-csv'),
    path('events/<int:event_id>/attendance-report/export-xlsx/', gate_views.event_attendance_report_export_xlsx, name='event-attendance-report-export-xlsx'),
    path('events/<int:event_id>/attendance-report/export-pdf/', gate_views.event_attendance_report_export_pdf, name='event-attendance-report-export-pdf'),
    path('events/<int:event_id>/scan-logs/export-csv/', gate_views.event_scan_logs_export_csv, name='event-scan-logs-export-csv'),
    path('events/<int:event_id>/scan-logs/export-xlsx/', gate_views.event_scan_logs_export_xlsx, name='event-scan-logs-export-xlsx'),
    path('events/<int:event_id>/currently-inside/', gate_views.event_currently_inside, name='event-currently-inside'),
    path('events/<int:event_id>/live/', gate_views.event_live_dashboard, name='event-live-dashboard'),
    path('events/<int:event_id>/expected-today/', gate_views.event_expected_today, name='event-expected-today'),
    path('events/<int:event_id>/manual-checkin/', gate_views.event_manual_checkin, name='event-manual-checkin'),
    path('events/<int:event_id>/field-trip-scan/', gate_views.field_trip_event_scan, name='event-field-trip-scan'),
    path('reports/compare-events/', gate_views.report_compare_events, name='report-compare-events'),
    path('audit-log/', gate_views.audit_log_viewer, name='audit-log-viewer'),
    path('audit-log/block-ip/', gate_views.block_ip, name='block-ip'),
    path('audit-log/unblock-ip/', gate_views.unblock_ip, name='unblock-ip'),
    path('audit-log/delete-blocked-ip/', gate_views.delete_blocked_ip, name='delete-blocked-ip'),
    path('visitor-pass/create/', gate_views.visitor_pass_create, name='visitor-pass-create'),
    path('visitor-qr/print-all/', gate_views.visitor_pass_print_all, name='visitor-pass-print-all'),
    path('visitor-qr/<str:code>/', gate_views.visitor_pass_qr_image, name='visitor-qr-image'),
    path('visitor-qr/<str:code>/card/', gate_views.visitor_pass_card, name='visitor-pass-card'),
    path('calendar.ics', gate_views.calendar_ics, name='calendar-ics'),
    # Staff/personnel gate APIs (JSON) + admin broadcast (separate from legacy "guard account" UI)
    path('api/student-lookup/', gate_personnel_views.quick_student_lookup_view, name='gate-api-student-lookup'),
    path('api/dashboard-stats/', gate_personnel_views.dashboard_stats_api_view, name='gate-api-dashboard-stats'),
    path('api/scanner-heartbeat/', gate_personnel_views.scanner_heartbeat_view, name='gate-scan-scanner-heartbeat'),
    path('api/guard-incident-report/', gate_personnel_views.guard_incident_report_view, name='gate-api-guard-incident-report'),
    path('api/guard-dashboard/', gate_personnel_views.guard_dashboard_data_view, name='gate-guard-dashboard-data'),
    path('api/poll-personnel-notifications/', gate_personnel_views.check_new_notifications_api_view, name='gate-api-poll-personnel-notifications'),
    path('api/personnel-notifications/mark-read/', gate_personnel_views.mark_notification_read_view, name='gate-api-personnel-notification-mark-read'),
    path('api/personnel-notifications/mark-all-read/', gate_personnel_views.mark_all_notifications_read_view, name='gate-api-personnel-notification-mark-all-read'),
    path('admin/broadcast-notification/', gate_personnel_views.admin_send_gate_notification_view, name='admin-send-gate-notification'),
    path('reports/today/', gate_views.gate_today_report, name='gate-today-report'),
    path('student-portal/', gate_views.student_portal, name='student-portal'),
    # Reports
    path('reports/', gate_views.reports_overview, name='reports-hub'),
    path('reports/overview/', gate_views.reports_overview, name='reports-overview'),
    path('reports/daily-gate/', gate_views.reports_daily_gate, name='reports-daily-gate'),
    path('reports/event-attendance/', gate_views.reports_event_attendance, name='reports-event-attendance'),
    path('reports/incidents-overrides/', gate_views.reports_incidents_overrides_redirect, name='reports-incidents-overrides'),
    path('reports/exports/', gate_views.reports_exports, name='reports-exports'),
    path('reports/exports/download/', gate_views.reports_export_download, name='reports-export-download'),
    path('reports/legacy/', gate_views.reports_hub, name='reports-hub-legacy'),
    path('reports/list/', gate_views.report_list, name='report-list'),
    path('reports/<int:pk>/download/', gate_views.report_download, name='report-download'),
    path('reports/on-demand/view/<int:pk>/', gate_views.report_on_demand_view, name='report-on-demand-view'),
    path('reports/on-demand/', gate_views.report_on_demand, name='report-on-demand'),
    # Optional read-only API for attendance integration (token in API_ATTENDANCE_TOKEN)
    path('api/attendance/', gate_views.api_attendance, name='api-attendance'),
    path('api/notification-count/', gate_views.api_notification_count, name='api-notification-count'),
    path('api/notifications/mark-all-read/', gate_views.notifications_mark_all_read, name='notifications-mark-all-read'),
    path('admin/notifications/check-new/', gate_views.check_new_admin_notifications_api_view, name='admin-check-new-notifications'),
]

