"""Gate Access & Attendance - City College of Bayawan."""
from django.urls import path
from . import gate_views
from . import guard_views

urlpatterns = [
    path('', gate_views.gate_scan, name='gate-scan'),
    path('sw.js', gate_views.gate_scan_sw, name='gate-scan-sw'),
    path('save-scan/', gate_views.save_scan, name='save_scan'),
    path('scan-event/', gate_views.scan_event_qr, name='scan_event_qr'),
    path('record-early-out/', gate_views.record_early_out, name='record_early_out'),
    path('visitor-checkin/', gate_views.visitor_checkin_submit, name='visitor-checkin-submit'),
    path('visitor-checkout/', gate_views.visitor_checkout_submit, name='visitor-checkout-submit'),
    path('visitor-force-checkout/', gate_views.visitor_force_checkout, name='visitor-force-checkout'),
    path('visitor-disable-pass/', gate_views.visitor_disable_pass, name='visitor-disable-pass'),
    path('record-visitor/', gate_views.record_visitor_entry, name='gate-record-visitor'),
    path('register-student/', gate_views.register_student_from_scan, name='gate-register-student'),
    path('lookup/', gate_views.lookup_student, name='gate-lookup'),
    path('record/', gate_views.record_entry, name='gate-record'),
    path('mark-participation/', gate_views.mark_participation, name='gate-mark-participation'),
    path('analytics/', gate_views.analytics_dashboard, name='gate-analytics'),
    path('analytics/report/', gate_views.analytics_report, name='gate-analytics-report'),
    path('students/', gate_views.student_list, name='gate-student-list'),
    path('users/pending-staff-guard/', gate_views.pending_staff_guard_list, name='pending-staff-guard-list'),
    path('students/approve-all-pending/', gate_views.approve_all_pending_students, name='gate-student-approve-all-pending'),
    path('students/export-csv/', gate_views.student_list_export_csv, name='gate-student-export-csv'),
    path('students/import-csv/', gate_views.import_students_csv, name='gate-student-import'),
    path('students/sample-50.csv', gate_views.student_sample_csv, name='gate-student-sample-csv'),
    path('students/create/', gate_views.student_create, name='gate-student-create'),
    path('students/<int:pk>/edit/', gate_views.student_edit, name='gate-student-edit'),
    path('students/<int:student_pk>/load-slips/', gate_views.load_slip_list, name='gate-load-slip-list'),
    path('students/<int:student_pk>/load-slips/add/', gate_views.load_slip_create, name='gate-load-slip-create'),
    path('students/<int:student_pk>/load-slips/<int:slip_pk>/edit/', gate_views.load_slip_edit, name='gate-load-slip-edit'),
    path('students/<int:student_pk>/load-slips/<int:slip_pk>/export.csv', gate_views.load_slip_export_csv, name='gate-load-slip-export-csv'),
    path('load-slips/upload/', gate_views.load_slip_upload, name='gate-load-slip-upload'),
    path('load-slips/import-errors.csv', gate_views.load_slip_import_errors_csv, name='gate-load-slip-import-errors-csv'),
    path('load-slips/template.csv', gate_views.load_slip_template_csv, name='gate-load-slip-template-csv'),
    path('load-slips/sample-batch-50.csv', gate_views.load_slip_sample_batch_csv, name='gate-load-slip-sample-batch-csv'),
    path('students/<int:pk>/qr/', gate_views.student_qr_image, name='gate-student-qr'),
    path('students/<int:pk>/eid/', gate_views.student_eid_card, name='gate-student-eid'),
    path('students/eid/print-all/', gate_views.student_eid_print_all, name='gate-student-eid-print-all'),
    path('entries/', gate_views.entry_list, name='gate-entry-list'),
    path('entries/event-attendees/', gate_views.event_attendees_embed, name='gate-event-attendees-embed'),
    path('visitors/', gate_views.visitor_entry_list, name='gate-visitor-list'),
    path('visitors/yearly/', gate_views.visitor_yearly_summary, name='gate-visitor-yearly'),
    path('incidents/', gate_views.incident_list, name='gate-incident-list'),
    path('incidents/report-proxy/', gate_views.report_proxy_attendance, name='gate-incident-report-proxy'),
    # Event attendance (token-based QR)
    path('events/attendance-scanner/', gate_views.event_attendance_scanner, name='event-attendance-scanner'),
    path('events/<int:event_id>/registrations/', gate_views.event_manage_registrations, name='event-manage-registrations'),
    path('events/<int:event_id>/registrations/export-csv/', gate_views.event_registrations_export_csv, name='event-registrations-export-csv'),
    path('events/<int:event_id>/attendance-report/', gate_views.event_attendance_report, name='event-attendance-report'),
    path('events/<int:event_id>/attendance-report/export-csv/', gate_views.event_attendance_report_export_csv, name='event-attendance-report-export-csv'),
    path('events/<int:event_id>/attendance-report/export-xlsx/', gate_views.event_attendance_report_export_xlsx, name='event-attendance-report-export-xlsx'),
    path('events/<int:event_id>/attendance-report/export-pdf/', gate_views.event_attendance_report_export_pdf, name='event-attendance-report-export-pdf'),
    path('events/<int:event_id>/scan-logs/export-csv/', gate_views.event_scan_logs_export_csv, name='event-scan-logs-export-csv'),
    path('events/<int:event_id>/scan-logs/export-xlsx/', gate_views.event_scan_logs_export_xlsx, name='event-scan-logs-export-xlsx'),
    path('events/<int:event_id>/currently-inside/', gate_views.event_currently_inside, name='event-currently-inside'),
    path('events/<int:event_id>/live/', gate_views.event_live_dashboard, name='event-live-dashboard'),
    path('events/<int:event_id>/expected-today/', gate_views.event_expected_today, name='event-expected-today'),
    path('events/<int:event_id>/manual-checkin/', gate_views.event_manual_checkin, name='event-manual-checkin'),
    path('events/<int:event_id>/field-trip-scan/', gate_views.field_trip_event_scan, name='event-field-trip-scan'),
    path('reports/compare-events/', gate_views.report_compare_events, name='report-compare-events'),
    path('audit-log/', gate_views.audit_log_viewer, name='audit-log-viewer'),
    path('audit-log/block-ip/', gate_views.block_ip, name='block-ip'),
    path('audit-log/unblock-ip/', gate_views.unblock_ip, name='unblock-ip'),
    path('audit-log/delete-blocked-ip/', gate_views.delete_blocked_ip, name='delete-blocked-ip'),
    path('guard-activity/', gate_views.guard_activity, name='guard-activity'),
    path('visitor-pass/create/', gate_views.visitor_pass_create, name='visitor-pass-create'),
    path('visitor-qr/print-all/', gate_views.visitor_pass_print_all, name='visitor-pass-print-all'),
    path('visitor-qr/<str:code>/', gate_views.visitor_pass_qr_image, name='visitor-qr-image'),
    path('visitor-qr/<str:code>/card/', gate_views.visitor_pass_card, name='visitor-pass-card'),
    path('calendar.ics', gate_views.calendar_ics, name='calendar-ics'),
    # Guard dashboard (consolidated - using enhanced version)
    path('guard/dashboard/', guard_views.guard_dashboard_view, name='guard-dashboard'),
    path('guard/clock-in/', guard_views.guard_clock_in_view, name='guard-clock-in'),
    path('guard/clock-out/', guard_views.guard_clock_out_view, name='guard-clock-out'),
    # Guard enhancement URLs
    path('guard/entries/', guard_views.guard_entry_list_view, name='guard-entry-list'),
    path('guard/notifications/', guard_views.guard_notifications_view, name='guard-notifications'),
    path('guard/notifications/mark-read/', guard_views.mark_notification_read_view, name='guard-notification-mark-read'),
    path('guard/notifications/mark-all-read/', guard_views.mark_all_notifications_read_view, name='guard-notification-mark-all-read'),
    path('guard/performance/', guard_views.guard_performance_view, name='guard-performance'),
    path('guard/student-lookup/', guard_views.quick_student_lookup_view, name='guard-student-lookup'),
    path('guard/dashboard/stats/', guard_views.dashboard_stats_api_view, name='guard-dashboard-stats-api'),
    path('guard/notifications/check-new/', guard_views.check_new_notifications_api_view, name='guard-check-new-notifications'),
    path('guard/activity-log/', guard_views.guard_activity_log_view, name='guard-activity-log'),
    path('guard/notifications/send/', guard_views.admin_send_guard_notification_view, name='admin-send-guard-notification'),
    path('reports/today/', gate_views.guard_today_report, name='guard-today-report'),
    path('student-portal/', gate_views.student_portal, name='student-portal'),
    # Reports
    path('reports/', gate_views.reports_overview, name='reports-hub'),
    path('reports/overview/', gate_views.reports_overview, name='reports-overview'),
    path('reports/daily-gate/', gate_views.reports_daily_gate, name='reports-daily-gate'),
    path('reports/event-attendance/', gate_views.reports_event_attendance, name='reports-event-attendance'),
    path('reports/incidents-overrides/', gate_views.reports_incidents_overrides, name='reports-incidents-overrides'),
    path('reports/exports/', gate_views.reports_exports, name='reports-exports'),
    path('reports/exports/download/', gate_views.reports_export_download, name='reports-export-download'),
    path('reports/legacy/', gate_views.reports_hub, name='reports-hub-legacy'),
    path('reports/list/', gate_views.report_list, name='report-list'),
    path('reports/<int:pk>/download/', gate_views.report_download, name='report-download'),
    path('reports/on-demand/view/<int:pk>/', gate_views.report_on_demand_view, name='report-on-demand-view'),
    path('reports/on-demand/', gate_views.report_on_demand, name='report-on-demand'),
    # Optional read-only API for attendance integration (token in API_ATTENDANCE_TOKEN)
    path('api/attendance/', gate_views.api_attendance, name='api-attendance'),
    path('api/notification-count/', gate_views.api_notification_count, name='api-notification-count'),
    path('api/notifications/mark-all-read/', gate_views.notifications_mark_all_read, name='notifications-mark-all-read'),
    path('admin/notifications/check-new/', gate_views.check_new_admin_notifications_api_view, name='admin-check-new-notifications'),
]

